from io import BytesIO
import logging
import threading
import time
import pasteboard

from pyobjus import autoclass
from pyobjus.dylib_manager import load_framework

load_framework("/System/Library/Frameworks/AppKit.framework")
_NSPasteboard = autoclass("NSPasteboard")

# nspasteboard.org convention: a clipboard manager (Raycast's history capture
# included) must not record an item declaring any of these types. A 1Password
# copy declares ConcealedType; upstream never checked for it, so a
# password-manager copy would sync in plaintext to the peer machine and land
# in its Raycast history. This is the gating fix for that leak.
CONCEALED_PASTEBOARD_TYPES = frozenset(
    {
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    }
)

_clipboard_thread = None
_callback_update = None
_run = False
_first_run = False
_block_image_once = False
_pasteboard_lock = threading.Lock()
_pb_writer = None


def is_concealed_types(declared_types) -> bool:
    """True if any of the given pasteboard UTIs marks a concealed, transient,
    or auto-generated item (see CONCEALED_PASTEBOARD_TYPES)."""
    return not CONCEALED_PASTEBOARD_TYPES.isdisjoint(declared_types)


def general_pasteboard_declared_types() -> set:
    types = _NSPasteboard.generalPasteboard().types
    return {types.objectAtIndex_(i).UTF8String() for i in range(types.count())}


def is_source_pasteboard_concealed() -> bool:
    """Checked before publishing any clipboard change (text/image/files).
    Fails closed — a read error is treated as concealed, since a broken type
    check must never fall through to publishing a possibly-concealed item."""
    try:
        return is_concealed_types(general_pasteboard_declared_types())
    except Exception as e:
        logging.error(f"Failed to read general pasteboard declared types: {e}")
        return True


def write_to_pasteboard(data, pb_type, declared_types=None):
    # declared_types: the pasteboard UTIs the incoming item was marked with,
    # when the caller has that information. Today's wire protocol carries no
    # per-item type metadata, so this only fires for a caller that explicitly
    # passes it — defense-in-depth, per the fork's contract that a received
    # concealed item is never stored locally even if one somehow arrives.
    if declared_types is not None and is_concealed_types(declared_types):
        logging.info(
            "Skipping pasteboard write — received item is a concealed pasteboard type"
        )
        return
    global _pb_writer
    with _pasteboard_lock:
        if _pb_writer is None:
            _pb_writer = pasteboard.Pasteboard()
        _pb_writer.set_contents(data, pb_type)


def _runner(enable_image_monitoring=False, enable_file_monitoring=False):
    global _first_run, _block_image_once
    try:
        pb_text = pasteboard.Pasteboard()
        if enable_image_monitoring:
            pb_image_png = pasteboard.Pasteboard()
            pb_image_tiff = pasteboard.Pasteboard()
        if enable_file_monitoring:
            pb_files = pasteboard.Pasteboard()
        image_processed = False
        files_processed = False
        while _run:
            # don't change the execution order (files,text,image or files,image,text)

            if enable_file_monitoring:
                # Files
                with _pasteboard_lock:
                    clipboard_files = pb_files.get_file_urls(diff=True)
                if (
                    clipboard_files is not None
                    and type(clipboard_files) is tuple
                    and len(clipboard_files) > 0
                ):
                    if (
                        _callback_update
                        and not _first_run
                        and not is_source_pasteboard_concealed()
                    ):
                        files_processed = True
                        _callback_update("files", clipboard_files)

            # Text
            with _pasteboard_lock:
                clipboard_text = pb_text.get_contents(
                    type=pasteboard.String, diff=True
                ) # If True, retrieves and returns the content only if it has changed since the last call.
                # This approach is efficient even in cases of frequent polling.
            if (
                clipboard_text is not None
                and type(clipboard_text) is str
                and len(clipboard_text) > 0
            ):
                if (
                    _callback_update
                    and not _first_run
                    and not files_processed
                    and not is_source_pasteboard_concealed()
                ):
                    _callback_update("text", clipboard_text)

            if enable_image_monitoring:
                # Image (PNG)
                with _pasteboard_lock:
                    clipboard_image_png = pb_image_png.get_contents(
                        type=pasteboard.PNG, diff=True
                    )
                if (
                    clipboard_image_png is not None
                    and type(clipboard_image_png) is bytes
                ):
                    if _callback_update and not _first_run and not image_processed:
                        image_processed = True
                        if _block_image_once:
                            _block_image_once = False
                        else:
                            if not files_processed and not is_source_pasteboard_concealed():
                                _callback_update("image", clipboard_image_png)

                # Image (TIFF)
                with _pasteboard_lock:
                    clipboard_image_tiff = pb_image_tiff.get_contents(
                        type=pasteboard.TIFF, diff=True
                    )
                if (
                    clipboard_image_tiff is not None
                    and type(clipboard_image_tiff) is bytes
                ):
                    if _callback_update and not _first_run and not image_processed:
                        image_processed = True
                        if _block_image_once:
                            _block_image_once = False
                        else:
                            if not files_processed and not is_source_pasteboard_concealed():
                                _callback_update("image", clipboard_image_tiff)

            files_processed = False
            image_processed = False
            _first_run = False
            time.sleep(0.3)  # seconds

    except Exception as e:
        logging.error(f"Error processing clipboard update: {e}")


def _start(enable_image_monitoring=False, enable_file_monitoring=False):
    global _clipboard_thread, _run, _first_run
    if not _clipboard_thread:
        _run = True
        _first_run = True
        _clipboard_thread = threading.Thread(
            target=_runner,
            args=(enable_image_monitoring, enable_file_monitoring),
            daemon=True,
        )
        _clipboard_thread.start()


def stop():
    global _clipboard_thread, _callback_update, _run, _first_run, _block_image_once, _pb_writer
    if _clipboard_thread:
        _run = False
        _clipboard_thread.join()  # Wait for the thread to finish
        _first_run = False
        _clipboard_thread = None
        _callback_update = None
        _block_image_once = False
        _pb_writer = None
        logging.info("Clipboard monitor stopped")


def wait():
    global _clipboard_thread
    if _clipboard_thread:
        _clipboard_thread.join()


def enable_block_image_once():
    global _block_image_once
    _block_image_once = True


def on_update(callback, enable_image_monitoring=False, enable_file_monitoring=False):
    global _callback_update
    _callback_update = callback
    _start(enable_image_monitoring, enable_file_monitoring)
