"""Unit tests for the concealed-pasteboard-type guard in clipboard_monitor_mac.

Run from ClipCascade_Desktop/src/:
    python3 -m unittest test.test_clipboard_monitor_mac -v
"""
import os
import sys
import time
import unittest
from unittest.mock import MagicMock, patch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from clipboard import clipboard_monitor_mac as monitor


class TestIsConcealedTypes(unittest.TestCase):
    def test_concealed_type_alone(self):
        self.assertTrue(
            monitor.is_concealed_types({"org.nspasteboard.ConcealedType"})
        )

    def test_transient_type_alone(self):
        self.assertTrue(
            monitor.is_concealed_types({"org.nspasteboard.TransientType"})
        )

    def test_auto_generated_type_alone(self):
        self.assertTrue(
            monitor.is_concealed_types({"org.nspasteboard.AutoGeneratedType"})
        )

    def test_concealed_type_mixed_with_normal_types(self):
        self.assertTrue(
            monitor.is_concealed_types(
                {"public.utf8-plain-text", "org.nspasteboard.ConcealedType"}
            )
        )

    def test_no_concealed_type(self):
        self.assertFalse(
            monitor.is_concealed_types({"public.utf8-plain-text", "public.png"})
        )

    def test_empty_types(self):
        self.assertFalse(monitor.is_concealed_types(set()))


def _mock_general_pasteboard(declared_type_strings):
    """Build a mock matching the pyobjus NSPasteboard shape this module reads:
    generalPasteboard().types.objectAtIndex_(i).UTF8String() per index, with
    .count() giving the length — mirrors the live API confirmed against a
    real NSPasteboard (attribute access, not a call, resolves the selector)."""
    mock_types = MagicMock()
    mock_types.count.return_value = len(declared_type_strings)

    def object_at_index(i):
        s = MagicMock()
        s.UTF8String.return_value = declared_type_strings[i]
        return s

    mock_types.objectAtIndex_.side_effect = object_at_index
    mock_pasteboard = MagicMock()
    mock_pasteboard.types = mock_types
    return mock_pasteboard


class TestIsSourcePasteboardConcealed(unittest.TestCase):
    """Parameterized on the spec's example table (one row per distinct
    'Pasteboard declares' value; the branch column is covered separately in
    TestRunnerGating since this check is identical across all branches)."""

    def _run_with_declared_types(self, declared_type_strings):
        mock_pb = _mock_general_pasteboard(declared_type_strings)
        with patch.object(
            monitor._NSPasteboard, "generalPasteboard", return_value=mock_pb
        ):
            return monitor.is_source_pasteboard_concealed()

    def test_concealed_type_blocks_publish(self):
        self.assertTrue(
            self._run_with_declared_types(
                ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]
            )
        )

    def test_transient_type_blocks_publish(self):
        self.assertTrue(
            self._run_with_declared_types(
                ["public.utf8-plain-text", "org.nspasteboard.TransientType"]
            )
        )

    def test_auto_generated_type_blocks_publish(self):
        self.assertTrue(
            self._run_with_declared_types(
                ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]
            )
        )

    def test_non_concealed_item_allows_publish(self):
        self.assertFalse(
            self._run_with_declared_types(
                ["public.utf8-plain-text", "NSStringPboardType"]
            )
        )

    def test_read_error_fails_closed(self):
        with patch.object(
            monitor._NSPasteboard,
            "generalPasteboard",
            side_effect=RuntimeError("pasteboard read failed"),
        ):
            self.assertTrue(monitor.is_source_pasteboard_concealed())


class TestRunnerGating(unittest.TestCase):
    """Drives the real _runner() loop with a mocked pasteboard.Pasteboard to
    confirm the guard applies to the text, image, and files branches — not
    just the shared gate function in isolation."""

    def setUp(self):
        monitor._run = False
        monitor._first_run = False
        monitor._callback_update = None
        monitor._clipboard_thread = None

    def tearDown(self):
        monitor.stop()

    @staticmethod
    def _second_call_then_none(value):
        """_runner's first poll is always discarded (_first_run): the
        callback-eligible read is the *second* call. Counting calls (rather
        than a fixed-length side_effect list) survives however many extra
        iterations the loop makes before the test thread signals it to stop."""
        call_count = 0

        def _side_effect(*_args, **_kwargs):
            nonlocal call_count
            call_count += 1
            return value if call_count == 2 else None

        return _side_effect

    def _drive_runner_once(self, text=None, image_png=None, files=None, concealed=False):
        received = []
        monitor._callback_update = lambda type_, content: received.append((type_, content))

        mock_pb_text = MagicMock()
        mock_pb_text.get_contents.side_effect = self._second_call_then_none(text)
        mock_pb_image_png = MagicMock()
        mock_pb_image_png.get_contents.side_effect = self._second_call_then_none(image_png)
        mock_pb_image_tiff = MagicMock()
        mock_pb_image_tiff.get_contents.return_value = None
        mock_pb_files = MagicMock()
        mock_pb_files.get_file_urls.side_effect = self._second_call_then_none(files)

        # Real 0.3s poll cadence (not mocked): _runner's second iteration —
        # where the discarded-first-poll value above becomes callback-eligible
        # — lands just after the first sleep(0.3) completes.
        with patch("clipboard.clipboard_monitor_mac.pasteboard.Pasteboard") as MockPB, \
             patch.object(monitor, "is_source_pasteboard_concealed", return_value=concealed):
            MockPB.side_effect = [
                mock_pb_text,
                mock_pb_image_png,
                mock_pb_image_tiff,
                mock_pb_files,
            ]
            monitor._first_run = True
            monitor._run = True
            monitor._clipboard_thread = None
            thread = __import__("threading").Thread(
                target=monitor._runner, args=(True, True), daemon=True
            )
            monitor._clipboard_thread = thread
            thread.start()
            time.sleep(0.5)
            monitor._run = False
            thread.join(timeout=2)

        return received

    def test_concealed_text_is_not_published(self):
        received = self._drive_runner_once(text="s3cr3t", concealed=True)
        self.assertEqual(received, [])

    def test_non_concealed_text_is_published(self):
        received = self._drive_runner_once(text="hello world", concealed=False)
        self.assertIn(("text", "hello world"), received)

    def test_concealed_image_is_not_published(self):
        received = self._drive_runner_once(image_png=b"\x89PNG", concealed=True)
        self.assertEqual(received, [])

    def test_non_concealed_image_is_published(self):
        received = self._drive_runner_once(image_png=b"\x89PNG", concealed=False)
        self.assertIn(("image", b"\x89PNG"), received)

    def test_concealed_files_are_not_published(self):
        received = self._drive_runner_once(files=("/tmp/a.txt",), concealed=True)
        self.assertEqual(received, [])

    def test_non_concealed_files_are_published(self):
        received = self._drive_runner_once(files=("/tmp/a.txt",), concealed=False)
        self.assertIn(("files", ("/tmp/a.txt",)), received)


class TestWriteToPasteboardGuard(unittest.TestCase):
    """Task 2.2: a received item explicitly marked concealed is dropped
    rather than written locally (defense-in-depth — see the docstring on
    write_to_pasteboard for why the wire protocol can't carry this today)."""

    def setUp(self):
        monitor._pb_writer = None

    def test_declared_concealed_type_is_not_written(self):
        with patch("clipboard.clipboard_monitor_mac.pasteboard.Pasteboard") as MockPB:
            mock_writer = MagicMock()
            MockPB.return_value = mock_writer
            monitor.write_to_pasteboard(
                "s3cr3t", "String", declared_types={"org.nspasteboard.ConcealedType"}
            )
            mock_writer.set_contents.assert_not_called()

    def test_no_declared_types_writes_normally(self):
        with patch("clipboard.clipboard_monitor_mac.pasteboard.Pasteboard") as MockPB:
            mock_writer = MagicMock()
            MockPB.return_value = mock_writer
            monitor.write_to_pasteboard("hello", "String", declared_types=None)
            mock_writer.set_contents.assert_called_once_with("hello", "String")

    def test_non_concealed_declared_types_writes_normally(self):
        with patch("clipboard.clipboard_monitor_mac.pasteboard.Pasteboard") as MockPB:
            mock_writer = MagicMock()
            MockPB.return_value = mock_writer
            monitor.write_to_pasteboard(
                "hello", "String", declared_types={"public.utf8-plain-text"}
            )
            mock_writer.set_contents.assert_called_once_with("hello", "String")


if __name__ == "__main__":
    unittest.main()
